# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Thu Jan 15 14:19:28 2015

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade


VERSION = "2015-01-15"

class AboutDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AboutDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_version = wx.StaticText(self, -1, "label_version")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AboutDialog.__set_properties
        self.SetTitle("About")
        self.SetSize((276, 226))
        # end wxGlade
        global VERSION
        self.label_version.SetLabel("Version: " + VERSION)


    def __do_layout(self):
        # begin wxGlade: AboutDialog.__do_layout
        sizer_18 = wx.BoxSizer(wx.VERTICAL)
        sizer_18.Add(self.label_version, 0, 0, 0)
        self.SetSizer(sizer_18)
        self.Layout()
        # end wxGlade

# end of class AboutDialog
