# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Tue Apr 05 10:46:12 2011

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class ExpenseDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ExpenseDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "id:")
        self.label_id = wx.StaticText(self, -1, "id")
        self.label_2 = wx.StaticText(self, -1, "period:")
        self.label_period = wx.StaticText(self, -1, "period")
        self.label_3 = wx.StaticText(self, -1, "jobcode:")
        self.choice_jobcode = wx.Choice(self, -1, choices=[])
        self.label_4 = wx.StaticText(self, -1, "task:")
        self.choice_task = wx.Choice(self, -1, choices=[])
        self.label_5 = wx.StaticText(self, -1, "desc:")
        self.txt_desc = wx.TextCtrl(self, -1, "")
        self.label_6 = wx.StaticText(self, -1, "amount:")
        self.txt_amount = wx.TextCtrl(self, -1, "")
        self.button_1 = wx.Button(self, -1, "Accept")
        self.button_discard = wx.Button(self, -1, "Discard")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.button_accept_clicked, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.button_discard_clicked, self.button_discard)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ExpenseDialog.__set_properties
        self.SetTitle("Expense")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ExpenseDialog.__do_layout
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.GridSizer(7, 2, 0, 0)
        grid_sizer_2.Add(self.label_1, 0, 0, 0)
        grid_sizer_2.Add(self.label_id, 0, 0, 0)
        grid_sizer_2.Add(self.label_2, 0, 0, 0)
        grid_sizer_2.Add(self.label_period, 0, 0, 0)
        grid_sizer_2.Add(self.label_3, 0, 0, 0)
        grid_sizer_2.Add(self.choice_jobcode, 0, 0, 0)
        grid_sizer_2.Add(self.label_4, 0, 0, 0)
        grid_sizer_2.Add(self.choice_task, 0, 0, 0)
        grid_sizer_2.Add(self.label_5, 0, 0, 0)
        grid_sizer_2.Add(self.txt_desc, 0, 0, 0)
        grid_sizer_2.Add(self.label_6, 0, 0, 0)
        grid_sizer_2.Add(self.txt_amount, 0, 0, 0)
        sizer_13.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        sizer_14.Add(self.button_1, 0, 0, 0)
        sizer_14.Add(self.button_discard, 0, 0, 0)
        sizer_13.Add(sizer_14, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_13)
        sizer_13.Fit(self)
        self.Layout()
        # end wxGlade

    def button_accept_clicked(self, event): # wxGlade: ExpenseDialog.<event_handler>
        print "Event handler `button_accept_clicked' not implemented!"
        event.Skip()

    def button_discard_clicked(self, event): # wxGlade: ExpenseDialog.<event_handler>
        print "Event handler `button_discard_clicked' not implemented!"
        event.Skip()

# end of class ExpenseDialog


