# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Fri Mar 25 14:56:12 2011

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

from common import princ
import expenses
import period
#import pydra

class ExpensesFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ExpensesFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_period = wx.StaticText(self, -1, "label_1")
        self.button_import_expenses_spreadsheet = wx.Button(self, -1, "SS")
        self.button_edit = wx.Button(self, -1, "Edit")
        self.list_expenses = wx.ListCtrl(self, -1, style=wx.LC_REPORT | wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.button_import_expenses_spreadsheet_clicked, self.button_import_expenses_spreadsheet)
        self.Bind(wx.EVT_BUTTON, self.button_edit_clicked, self.button_edit)
        # end wxGlade

        # added by mcarter
        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.Bind(wx.EVT_SHOW, self.OnOpen)
        
        self.list_expenses.DeleteAllColumns()
        self.list_expenses.InsertColumn(0, 'Period')
        self.list_expenses.InsertColumn(1, 'Jobcode')
        self.list_expenses.InsertColumn(2, 'Task')
        self.list_expenses.InsertColumn(3, 'Description', width = 400)
        self.list_expenses.InsertColumn(4, 'Amount')
        

    def OnClose(self, event):
        princ('OnClose - TODO maybe export to database')
        self.Hide()
        
    def OnOpen(self, event):
        if not self.IsShown(): return # this func is called on both opening and closing
        princ('OnShow - TODO: import from database tblCamelExpenses')
        
    def __set_properties(self):
        # begin wxGlade: ExpensesFrame.__set_properties
        self.SetTitle("Expenses")
        self.button_import_expenses_spreadsheet.SetToolTipString("Import from spreadsheet")
        self.list_expenses.SetMinSize((745, 391))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ExpensesFrame.__do_layout
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12.Add(self.label_period, 0, 0, 0)
        sizer_12.Add(self.button_import_expenses_spreadsheet, 0, 0, 0)
        sizer_12.Add(self.button_edit, 0, 0, 0)
        sizer_11.Add(sizer_12, 0, wx.EXPAND, 0)
        sizer_11.Add(self.list_expenses, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_11)
        sizer_11.Fit(self)
        self.Layout()
        # end wxGlade

    def button_import_expenses_spreadsheet_clicked(self, event): # wxGlade: ExpensesFrame.<event_handler>
        exps = expenses.read_expenses(period.g_period)
        for e in exps:
            per = period.g_period.yyyymm()
            jobcode = e['JobCode']
            task = e['Task']
            desc = ' - '.join([e['Period'], e['Name'], e['Desc']])
            amount = str(e['Amount'])
            seq = (per, jobcode, task, desc, amount)
            self.list_expenses.Append(seq)
        #princ(str(exps))

    def button_edit_clicked(self, event): # wxGlade: ExpensesFrame.<event_handler>
        print "Event handler `button_edit_clicked' not implemented"
        event.Skip()

# end of class ExpensesFrame


