# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Fri Feb 11 15:13:32 2011

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

import os

import win32api
#import wx
#import wx.richtext

import common
#import db
import period
import pydra
import rtfsprint

import JobsFrame

def open_file(filename):
    win32api.ShellExecute(0, "open", filename, None, ".", 0)
    
class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frmMain_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.menu_data_jobs = wx.MenuItem(wxglade_tmp_menu, wx.NewId(), "Jobs", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendItem(self.menu_data_jobs)
        self.frmMain_menubar.Append(wxglade_tmp_menu, "Data")
        self.SetMenuBar(self.frmMain_menubar)
        # Menu Bar end
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.btnAllStages = wx.Button(self.notebook_1_pane_1, -1, "All Stages")
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, -1)
        self.btnExpenses = wx.Button(self.notebook_1_pane_2, -1, "Expenses")
        self.btnGizmo = wx.Button(self.notebook_1_pane_2, -1, "Gizmo")
        self.btnInvoiceSummary = wx.Button(self.notebook_1_pane_2, -1, "Invoice Summary")
        self.btnOpenReportsFolder = wx.Button(self.notebook_1_pane_2, -1, "Open Reports Folder")
        self.btnHtml = wx.Button(self.notebook_1_pane_2, -1, "Html")
        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, -1)
        self.btnPrintWorkstatements = wx.Button(self.notebook_1_pane_3, -1, "Workstatements")
        self.btnPrintTimesheets = wx.Button(self.notebook_1_pane_3, -1, "Timesheets")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.menu_data_jobs_selected, self.menu_data_jobs)
        self.Bind(wx.EVT_BUTTON, self.click_all_stages, self.btnAllStages)
        self.Bind(wx.EVT_BUTTON, self.click_expenses, self.btnExpenses)
        self.Bind(wx.EVT_BUTTON, self.click_gizmo, self.btnGizmo)
        self.Bind(wx.EVT_BUTTON, self.click_invoice_summary, self.btnInvoiceSummary)
        self.Bind(wx.EVT_BUTTON, self.click_open_reports_folder, self.btnOpenReportsFolder)
        self.Bind(wx.EVT_BUTTON, self.click_html, self.btnHtml)
        self.Bind(wx.EVT_BUTTON, self.click_print_workstatements, self.btnPrintWorkstatements)
        self.Bind(wx.EVT_BUTTON, self.click_print_timesheets, self.btnPrintTimesheets)
        # end wxGlade
 

        # added by mcarter
        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.jobs_frame = JobsFrame.JobsFrame(self)

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Pydra GUI")
        self.SetSize((294, 218))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.btnAllStages, 0, 0, 0)
        self.notebook_1_pane_1.SetSizer(sizer_3)
        sizer_4.Add(self.btnExpenses, 0, 0, 0)
        sizer_4.Add(self.btnGizmo, 0, 0, 0)
        sizer_4.Add(self.btnInvoiceSummary, 0, 0, 0)
        sizer_4.Add(self.btnOpenReportsFolder, 0, 0, 0)
        sizer_4.Add(self.btnHtml, 0, 0, 0)
        self.notebook_1_pane_2.SetSizer(sizer_4)
        sizer_2.Add(self.btnPrintWorkstatements, 0, 0, 0)
        sizer_2.Add(self.btnPrintTimesheets, 0, 0, 0)
        self.notebook_1_pane_3.SetSizer(sizer_2)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Process")
        self.notebook_1.AddPage(self.notebook_1_pane_2, "Externals")
        self.notebook_1.AddPage(self.notebook_1_pane_3, "Printing")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def OnClose(self, event):        
        if self.jobs_frame.IsShown():
            wx.MessageBox("Close jobs form first", "Error")
        else:
            print "Going down"
            self.Destroy()
        
    def menu_data_jobs_selected(self, event): # wxGlade: MainFrame.<event_handler>
        if not self.jobs_frame.IsShown():
            self.jobs_frame.Show()

    def click_all_stages(self, event): # wxGlade: MainFrame.<event_handler>
        pydra.allstages()
        wx.MessageBox('Finished', 'Info')

    def click_expenses(self, event): # wxGlade: MainFrame.<event_handler>
        open_file(common.camelxls())

    def click_gizmo(self, event): # wxGlade: MainFrame.<event_handler>
        open_file('M:\\Finance\\gizmo\\gizmo04.xls')

    def click_invoice_summary(self, event): # wxGlade: MainFrame.<event_handler>
        p = period.Period(usePrev = True)
        fname = '"M:\\Finance\\Invoices\\Inv summaries {0}\\Inv Summary {1}.xls"'.format(p.y, p.yyyymm())
        open_file(fname)

    def click_open_reports_folder(self, event): # wxGlade: MainFrame.<event_handler>
        cmd = 'explorer ' + common.reportdir()
        os.system(cmd)

    def click_html(self, event): # wxGlade: MainFrame.<event_handler>
        open_file('M:\\Finance\\pypms\\texts.htm')

    def click_print_workstatements(self, event): # wxGlade: MainFrame.<event_handler>
        rtfsprint.work_statements()

    def click_print_timesheets(self, event): # wxGlade: MainFrame.<event_handler>
        rtfsprint.timesheets()
        wx.MessageBox('Finished', 'Info')

# end of class MainFrame


