#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Thu Jan 13 15:09:26 2011


# begin wxGlade: extracode
# end wxGlade

import os

import win32api
import wx
import wx.richtext

import common
import period
import pydra



class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.btnAllStages = wx.Button(self, -1, "All Stages")
        self.btnOpenReportsFolder = wx.Button(self, -1, "Open Reports Folder")
        self.btnPrintTimesheets = wx.Button(self, -1, "Print Timesheets")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.click_all_stages, self.btnAllStages)
        self.Bind(wx.EVT_BUTTON, self.click_open_reports_folder, self.btnOpenReportsFolder)
        self.Bind(wx.EVT_BUTTON, self.click_print_timesheets, self.btnPrintTimesheets)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.btnAllStages, 0, 0, 0)
        sizer_1.Add(self.btnOpenReportsFolder, 0, 0, 0)
        sizer_1.Add(self.btnPrintTimesheets, 0, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def click_print_timesheets(self, event): # wxGlade: MainFrame.<event_handler>
        # TODO
        rtp = wx.richtext.RichTextPrinting()
        rtp.PrintFile('M:\\Finance\\pypms\\out\\2010-12\\timesheets\\2605.rtf')
        event.Skip()

    def click_all_stages(self, event): # wxGlade: MainFrame.<event_handler>
        pydra.allstages()
        #print "Event handler `click_all_stages' not implemented"
        #event.Skip()

    def click_open_reports_folder(self, event): # wxGlade: MainFrame.<event_handler>        
        cmd = 'explorer ' +common.reportdir()
        print cmd
        os.system(cmd)
        #win32api.ShellExecute(0, "open", common.reportdir(), None, ".", 0)

# end of class MainFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frmMain = MainFrame(None, -1, "")
    app.SetTopWindow(frmMain)
    frmMain.Show()
    app.MainLoop()
