#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Thu Jan 13 15:09:26 2011

import wx

# begin wxGlade: extracode
# end wxGlade
import wx.richtext



class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.btnPrintTimesheets = wx.Button(self, -1, "Print Timesheets")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.click_print_timesheets, self.btnPrintTimesheets)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("frame_1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.btnPrintTimesheets, 0, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def click_print_timesheets(self, event): # wxGlade: MainFrame.<event_handler>
        # TODO
        rtp = wx.richtext.RichTextPrinting()
        rtp.PrintFile('M:\\Finance\\pypms\\out\\2010-12\\timesheets\\2605.rtf')
        event.Skip()

# end of class MainFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frmMain = MainFrame(None, -1, "")
    app.SetTopWindow(frmMain)
    frmMain.Show()
    app.MainLoop()
