# -*- coding: iso-8859-15 -*-
# generated by wxGlade HG on Thu Feb 24 16:17:32 2011

import wx

# begin wxGlade: dependencies
import wx.grid
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class TimegridFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TimegridFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.btnCalculate = wx.Button(self, -1, "Calculate")
        self.grid_time = wx.grid.Grid(self, -1, size=(1, 1))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.btn_calculate_clicked, self.btnCalculate)
        # end wxGlade
        
        # added by mcarter
        self.Bind(wx.EVT_CLOSE, self.OnClose)

    def OnClose(self, event):
        self.Hide()
        
    def __set_properties(self):
        # begin wxGlade: TimegridFrame.__set_properties
        self.SetTitle("Time grid")
        self.SetSize((1077, 522))
        self.grid_time.CreateGrid(0, 3)
        self.grid_time.SetColLabelValue(0, "IN")
        self.grid_time.SetColLabelValue(1, "NAME")
        self.grid_time.SetColLabelValue(2, "1")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: TimegridFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.btnCalculate, 0, 0, 0)
        sizer_2.Add(self.grid_time, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

    def btn_calculate_clicked(self, event): # wxGlade: TimegridFrame.<event_handler>
    
        grid = self.grid_time
        num_rows = grid.GetNumberRows()
        if num_rows >0:
            grid.DeleteRows(0, num_rows)
        
        # TODO fill this in
        grid.AppendRows(1)
        grid.SetCellValue(0,0, "One")
        grid.AppendRows(1)
        grid.SetCellValue(1,0, "Two")
        
        

# end of class TimegridFrame


